import { MaterialProcess, MaterialTouchSection, ProductComparison, TextilePetStorySection, WorkshopSection } from "@/components/sections/HomeSections";
import { EditorialBlocks, PageHero } from "@/components/sections/PageHero";
import { pageMetadata } from "@/lib/seo";
export const metadata=pageMetadata("La matière","Comprendre la matière issue de textiles industriels recyclés utilisée pour le corps du stylo.","/matiere");
export default function Page(){return <><section className="relative h-[100svh] min-h-[560px] w-full overflow-hidden bg-[#111820]" aria-label="Fabrication de la matière Un1qpen"><video className="size-full object-cover" src="/videos/fabrication-un1qpen.mp4" autoPlay muted loop playsInline controls preload="metadata">Votre navigateur ne permet pas de lire cette vidéo.</video><div className="pointer-events-none absolute inset-x-0 top-0 bg-gradient-to-b from-black/65 via-black/25 to-transparent px-6 pb-28 pt-32 text-white md:px-12 md:pt-36"><h1 className="max-w-4xl text-4xl font-semibold tracking-[-.045em] md:text-6xl">De la fibre textile à une nouvelle matière.</h1></div></section><TextilePetStorySection/><PageHero eyebrow="La matière" title="Transformer la fibre. Préserver son histoire." intro="Une matière élaborée principalement à partir de déchets textiles industriels fortement chargés en polyester."/><MaterialProcess/><WorkshopSection/><MaterialTouchSection/><EditorialBlocks blocks={[
  {title:"Une origine industrielle",text:"Vêtements professionnels, nappes et textiles techniques peuvent constituer les flux utilisés. Ils sont principalement industriels ou post-industriels, et non collectés auprès des consommateurs."},
  {title:"Une sélection nécessaire",text:"La composition des textiles compte : les flux fortement chargés en polyester sont sélectionnés pour permettre leur transformation."},
  {title:"Des limites dites clairement",text:"La matière textile recyclée concerne aujourd’hui le corps du stylo. Le clip et les composants techniques emploient d’autres matières."}
]}/><ProductComparison/></>}
