import { ArrowDown, ArrowUpRight, Check, Factory, Fingerprint, Recycle, Sparkles } from "lucide-react";
import { AnimatedReveal } from "@/components/animations/AnimatedReveal";
import { Button, Card, Container, SectionHeading } from "@/components/ui";
import { statistics } from "@/data/statistics";
import { process } from "@/data/process";
import { productFeatures } from "@/data/product";
import { faqs } from "@/data/faq";

export function HeroSection() { return <section className="grid-texture relative flex min-h-[94svh] items-end overflow-hidden bg-[#182b3a] pb-16 pt-32 text-white">
  <div className="absolute right-[-5%] top-[29%] opacity-90"><div className="pen"><span className="pen-clip"/><span className="pen-copy">MON CORPS EST EN TEXTILE RECYCLÉ EN FRANCE</span></div></div>
  <Container className="relative z-10"><AnimatedReveal><p className="eyebrow !text-[#d5a184]">Innovation matière · objet média</p><h1 className="display mt-6 max-w-5xl">Le premier stylo qui écrit une nouvelle histoire au textile recyclé.</h1></AnimatedReveal>
  <AnimatedReveal delay={.15} className="mt-8 max-w-xl"><p className="text-lg leading-relaxed text-white/70">Un textile industriel destiné à être éliminé devient le corps d’un stylo conçu pour communiquer autrement.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="#decouvrir" variant="light">Découvrir UN1QPEN</Button><Button href="/contact?type=sample" variant="ghost">Demander un échantillon</Button></div></AnimatedReveal>
  <a href="#decouvrir" aria-label="Faire défiler" className="absolute bottom-0 right-0 grid size-12 place-items-center rounded-full border border-white/30"><ArrowDown size={18}/></a></Container>
</section>; }

export function ManifestoSection() { return <section id="decouvrir" className="section"><Container><AnimatedReveal><p className="max-w-6xl font-[var(--font-serif)] text-[clamp(2.7rem,6vw,6.5rem)] leading-[1.02] tracking-[-.04em]">« D’un textile industriel destiné à être éliminé, nous avons choisi d’écrire une autre destinée. »</p><p className="copy ml-auto mt-12 max-w-xl">UN1QPEN transforme une matière issue de déchets textiles industriels en un objet utile, personnalisable et visible au quotidien.</p></AnimatedReveal></Container></section>; }

const pillars = [
  [Recycle, "Textile recyclé", "Le corps utilise une matière issue de textiles industriels recyclés, fortement chargés en polyester."],
  [Sparkles, "Sans nouveau pétrole pour le corps", "Une matière existante remplace le plastique vierge pour cette partie du produit."],
  [Factory, "Fabrication européenne", "La matière est développée en France et le corps du stylo est injecté en Italie."],
  [Fingerprint, "Une histoire tangible", "Un support de communication concret, tactile et immédiatement compréhensible."],
];
export function ValuePillars() { return <section className="section bg-white"><Container><SectionHeading eyebrow="La proposition" title="Plus qu’un stylo recyclé : une histoire à transmettre."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{pillars.map(([Icon,title,text],i)=><AnimatedReveal delay={i*.06} key={String(title)}><Card className="h-full"><Icon size={24}/><h3 className="mt-8 text-xl font-semibold">{String(title)}</h3><p className="mt-4 leading-relaxed text-[#66645e]">{String(text)}</p></Card></AnimatedReveal>)}</div></Container></section>; }

export function KeyFigures() { return <section className="section bg-[#151515] text-white"><Container><SectionHeading eyebrow="Repères" title="Une innovation déjà concrète." copy="Des chiffres volontairement formulés avec précision, faciles à mettre à jour."/><div className="grid border-l border-white/20 sm:grid-cols-2 lg:grid-cols-4">{statistics.map(s=><div className="border-r border-t border-b border-white/20 p-7" key={s.value}><strong className="text-4xl text-[#d5a184]">{s.value}</strong><p className="mt-5 text-sm leading-relaxed text-white/60">{s.label}</p></div>)}</div></Container></section>; }

export function MaterialProcess() { return <section className="section"><Container><SectionHeading eyebrow="Transformation" title="Du textile à l’objet, en cinq gestes."/><ol className="grid gap-0 lg:grid-cols-5">{process.map(([n,t,d],i)=><AnimatedReveal delay={i*.08} key={n} className="relative border-l border-[#a46f52] p-6 lg:border-l-0 lg:border-t"><span className="text-xs font-bold text-[#a46f52]">{n}</span><h3 className="mt-7 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-[#66645e]">{d}</p></AnimatedReveal>)}</ol></Container></section>; }

export function EuropeOriginSection() { return <section className="section overflow-hidden bg-[#dcd8ce]"><Container className="grid items-center gap-14 lg:grid-cols-2"><div><SectionHeading eyebrow="Circuit européen" title="Un circuit industriel européen volontairement court." copy="La matière est développée en France. Le corps du stylo est injecté en Italie, dans une usine spécialisée dans la fabrication d’instruments d’écriture."/></div><div className="relative min-h-96 rounded-[2rem] bg-[#182b3a] p-8 text-white"><div className="absolute left-[25%] top-[40%]"><span className="block size-4 rounded-full bg-[#d5a184] ring-8 ring-[#d5a184]/20"/><b className="mt-3 block">Région lyonnaise</b><small>Matière · France</small></div><div className="absolute bottom-[26%] right-[22%]"><span className="block size-4 rounded-full bg-[#d5a184] ring-8 ring-[#d5a184]/20"/><b className="mt-3 block">Région de Turin</b><small>Injection · Italie</small></div><svg aria-hidden viewBox="0 0 400 300" className="h-full w-full opacity-20"><path fill="none" stroke="white" strokeWidth="2" d="M49 112l48-56 69 7 48-33 74 32 58 65-39 49 15 70-65 18-42-36-64 26-54-47z"/></svg></div></Container></section>; }

export function ProductShowcase() { return <section className="section bg-white"><Container><div className="grid items-center gap-16 lg:grid-cols-2"><div className="grid min-h-[520px] place-items-center overflow-hidden rounded-[2rem] bg-[#a46f52]"><div className="pen !w-[620px] !rotate-[-18deg] !bg-[#182b3a]"><span className="pen-clip !bg-[#d8d7d1]"/><span className="pen-copy">MON CORPS EST EN TEXTILE RECYCLÉ EN FRANCE</span></div></div><div><SectionHeading eyebrow="Le produit" title="Un objet utile, pensé pour être vu."/><ul className="grid gap-4">{productFeatures.map(f=><li className="flex gap-3" key={f}><Check className="mt-1 shrink-0 text-[#a46f52]" size={18}/>{f}</li>)}</ul><p className="copy mt-6 text-sm">Le clip et les éléments techniques ne sont actuellement pas fabriqués dans la matière textile recyclée.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/documents/fiche-technique-un1qpen.pdf">Télécharger la fiche technique</Button><Button href="/contact?type=sample" variant="ghost">Recevoir un échantillon</Button></div></div></div></Container></section>; }

export function MaterialTouchSection() { return <section className="section bg-[#a46f52] text-white"><Container><p className="eyebrow !text-white/60">Expérience matière</p><div className="mt-6 grid gap-12 lg:grid-cols-[1.4fr_.6fr]"><h2 className="h2">Une matière qui se remarque aussi au toucher.</h2><p className="text-lg leading-relaxed text-white/75">La matière épouse finement les détails du moule et donne au corps du stylo un aspect doux et soyeux, différent des plastiques classiques.</p></div></Container></section>; }

export function ProductComparison() { const rows=[["Plastique vierge","Matière neuve","Référence classique"],["Plastique recyclé","Plastique revalorisé","Alternative connue"],["UN1QPEN","Origine textile recyclée","Récit matière, toucher et circuit européen"]]; return <section className="section"><Container><SectionHeading eyebrow="La différence" title="Trois approches. Une origine singulière." copy="UN1QPEN complète les solutions existantes par l’origine textile de sa matière et la force de son récit."/><div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse text-left"><thead><tr className="border-b border-[#151515] text-xs uppercase tracking-widest"><th className="py-5">Solution</th><th>Origine du corps</th><th>Point distinctif</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r[0]} className={i===2?"bg-white font-semibold":"border-b border-[#d9d7d1]"}>{r.map(c=><td className="p-5" key={c}>{c}</td>)}</tr>)}</tbody></table></div></Container></section>; }

export function BrandVisionSection() { const cards=[["01","UN1QPEN","Premier modèle"],["02","UN2QPEN","Prochain développement · vision"],["∞","UN1Q Objects","Futurs objets · vision"]]; return <section className="section bg-[#182b3a] text-white"><Container><SectionHeading eyebrow="La vision" title="Le premier produit d’une nouvelle génération d’objets." copy="UN1QPEN est la première démonstration d’une ambition plus large : donner une nouvelle fonction à des matières issues de textiles recyclés et les transformer en objets utiles, désirables et personnalisables."/><div className="grid gap-4 md:grid-cols-3">{cards.map(c=><div key={c[1]} className="rounded-3xl border border-white/20 p-8"><span className="text-[#d5a184]">{c[0]}</span><h3 className="mt-20 text-2xl">{c[1]}</h3><p className="mt-2 text-sm text-white/50">{c[2]}</p></div>)}</div></Container></section>; }

export function ProfessionalSection() { const args=["Produit différenciant","Discours immédiatement compréhensible","Forte valeur narrative","Fabrication européenne","Personnalisation","Échantillons sur demande"]; return <section className="section bg-white"><Container><SectionHeading eyebrow="B2B" title="Une innovation pensée pour les professionnels de l’objet média."/><div className="grid gap-12 lg:grid-cols-2"><div className="grid grid-cols-2 gap-3">{args.map(a=><Card key={a}><p className="font-semibold">{a}</p></Card>)}</div><div className="self-center"><p className="copy">Un support visible, quotidien et pertinent pour les campagnes RSE, les lancements, les événements et la communication interne.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/contact?type=sample">Recevoir un échantillon</Button><Button href="/contact?type=partner" variant="ghost">Devenir partenaire</Button></div></div></div></Container></section>; }

export function UseCases() { const items=["Cadeau d’entreprise","Campagne RSE","Salon professionnel","Lancement de produit","Communication interne","Événement","Cadeau client","Kit de bienvenue","Sensibilisation au recyclage textile"]; return <section className="section"><Container><SectionHeading eyebrow="Cas d’usage" title="Une histoire à faire circuler."/><div className="flex flex-wrap gap-3">{items.map(i=><span className="rounded-full border border-[#aaa8a1] bg-white px-5 py-3 text-sm" key={i}>{i}</span>)}</div></Container></section>; }

export function QuoteSection() { return <section className="section bg-[#151515] text-center text-white"><Container><p className="eyebrow">UN1Q Manifesto</p><p className="mx-auto mt-8 max-w-5xl font-[var(--font-serif)] text-[clamp(3rem,7vw,7rem)] leading-none">Plus de solutions,<br/><span className="text-[#d5a184]">moins de pollution.</span></p><p className="mt-12 text-white/50">Moins de pétrole, plus d’idées.</p></Container></section>; }

export function FAQ() { return <section className="section bg-white"><Container><SectionHeading eyebrow="Questions fréquentes" title="Dire les choses clairement."/><div className="mx-auto max-w-4xl divide-y divide-[#d9d7d1]">{faqs.map(([q,a])=><details className="group py-6" key={q}><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-semibold">{q}<ArrowUpRight className="transition group-open:rotate-90"/></summary><p className="copy mt-4 pr-12 text-base">{a}</p></details>)}</div></Container></section>; }
